version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: netflix_backend
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: netflix_frontend
    ports:
      - "8501:8501"
    restart: always
    depends_on:
      - backend
